name: Run Java Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # позволяет запускать вручную

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build and run tests
        run: ./gradlew clean test
